# version: '3'
    # environment:
    #   KAFKA_BROKER: kafka:9093
# services:
  # microservices-bus:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    # depends_on:
    #   - service1
    #   - service2

  # service1:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-service1
    # ports:
    #   - "8081:8081"

  # service2:
    # build:
    #   context: .
    #   dockerfile: Dockerfile-service2
    # ports:
    #   - "8082:8082"

version: '3.8'

services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "microservices-topic:1:1"

  microservices-bus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # depends_on:
    #   - service1
    #   - service2
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9093

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service1
    ports:
      - "8081:8081"
    depends_on:
      - microservices-bus
    environment:
      KAFKA_BROKER: kafka:9093
      SERVICE_PORT: 8081

  service2:
    build:
      context: .
      dockerfile: Dockerfile-service2
    ports:
      - "8082:8082"
    depends_on:
      - microservices-bus
    environment:
      KAFKA_BROKER: kafka:9093
      SERVICE_PORT: 8082
