
# Use the official Golang image as the base image
FROM golang:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the Go application
RUN go build -o microservices/service2/main .

# Expose the port that your Go application will run on
EXPOSE 8082

# Command to run the executable
CMD ["microservices/service2/main"]
